build:
	@echo "Building..."
	@go build ./cmd/cal
	@echo "Building completed"

up:
	@echo "Running..."
	@start "" "/C/Program Files/Git/git-bash.exe" -c "./cal"
	@echo "Running completed"

build-up: build up