services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: ${APP_NAME}
        APP_TRANSPORT_HTTP_PORT: ${APP_TRANSPORT_HTTP_PORT}
    container_name: ${APP_CONTAINER}
    env_file:
      - .env
    environment:
      - APP_NAME=${APP_NAME}
      - APP_TRANSPORT_HTTP_PORT=${APP_TRANSPORT_HTTP_PORT}
      - APP_TRANSPORT_HTTP_PUBLIC_HOST=${APP_TRANSPORT_HTTP_PUBLIC_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_WEBHOOK_PATH=${TELEGRAM_WEBHOOK_PATH}
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
    ports:
      - "${APP_TRANSPORT_HTTP_PORT}:${APP_TRANSPORT_HTTP_PORT}"
    restart: unless-stopped
