MAKEFLAGS += --no-print-directory

app-build:
	@echo "Building delayed-notifier..."
	@go build ./cmd/delayed-notifier_main-server
	@echo "Building delayed-notifier completed"

app-up:
	@echo "Running delayed-notifier..."
	@start "" "/C/Program Files/Git/git-bash.exe" -c "./delayed-notifier_main-server"
	@sleep 1
	@echo "Running delayed-notifier completed"

app-build-up: app-build app-up
