server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: delayed-notifier_main-server
    static_configs:
      - targets: [localhost]
        labels:
          job: delayed-notifier_main-server
          app: delayed-notifier_main-server
          __path__: /var/log/myapp/*.log