server:
  http_listen_port: 9080
  grpc_listen_port: 0
 
positions:
  filename: /var/lib/promtail/positions.yaml
 
clients:
  - url: http://host.docker.internal:3100/loki/api/v1/push
 
scrape_configs:
  - job_name: delayed-notifier_main-server
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
 
    relabel_configs:
      - source_labels: [__meta_docker_container_log_stream]
        regex: stdout
        action: keep
 
      - source_labels: [__meta_docker_container_name]
        target_label: container
        regex: "/(.*)"
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: project
      - source_labels: [__meta_docker_container_label_com_docker_compose_container-number]
        target_label: container_number
      - target_label: job
        replacement: docker-stdout
 
    pipeline_stages:
      - docker: {}
 
      - json:
          expressions:
            level: level
            layer: layer
            component: component
            method: method
            message: message
            time: time
 
      - labels:
          level:
          layer:
          component:
          method:
 
      - output:
          source: message