server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: delayed-notifier_main-server
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: .*delayed-notifier_main-server_app.*
        action: keep

      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: project
      - target_label: job
        replacement: delayed-notifier_main-server

    pipeline_stages:
      - json:
          expressions:
            level: level
            layer: layer
            component: component
            method: method
            message: message
            time: time

      - labels:
          level:
          layer:
          component:
          method:

      - output:
          source: message
