services:
  pgauto-monitor:
    image: citusdata/pg_auto_failover:latest
    container_name: pgauto-monitor
    environment:
      PG_AUTOCTL_DEBUG: 1
    ports:
      - "3000:3000"
    command: >
      pg_autoctl create monitor
      --pgdata /var/lib/postgresql/monitor
      --pgport 5432
      --nodename pgauto-monitor
      --hostname pgauto-monitor
    networks:
      - pgauto-network
    volumes:
      - pgauto-monitor-data:/var/lib/postgresql/monitor

  pgauto-node1:
    image: citusdata/pg_auto_failover:latest
    container_name: pgauto-node1
    environment:
      PG_AUTOCTL_DEBUG: 1
      PG_AUTOCTL_MONITOR: "postgres://autoctl_node@pgauto-monitor:5432/pg_auto_failover"
    ports:
      - "5432:5432"
    command: >
      pg_autoctl create postgres
      --pgdata /var/lib/postgresql/node1
      --pgport 5432
      --nodename pgauto-node1
      --hostname pgauto-node1
      --name node1
    depends_on:
      - pgauto-monitor
    networks:
      - pgauto-network
    volumes:
      - pgauto-node1-data:/var/lib/postgresql/node1

  pgauto-node2:
    image: citusdata/pg_auto_failover:latest
    container_name: pgauto-node2
    environment:
      PG_AUTOCTL_DEBUG: 1
      PG_AUTOCTL_MONITOR: "postgres://autoctl_node@pgauto-monitor:5432/pg_auto_failover"
    ports:
      - "5433:5432"
    command: >
      pg_autoctl create postgres
      --pgdata /var/lib/postgresql/node2
      --pgport 5432
      --nodename pgauto-node2
      --hostname pgauto-node2
      --name node2
    depends_on:
      - pgauto-monitor
    networks:
      - pgauto-network
    volumes:
      - pgauto-node2-data:/var/lib/postgresql/node2

  pgauto-node3:
    image: citusdata/pg_auto_failover:latest
    container_name: pgauto-node3
    environment:
      PG_AUTOCTL_DEBUG: 1
      PG_AUTOCTL_MONITOR: "postgres://autoctl_node@pgauto-monitor:5432/pg_auto_failover"
    ports:
      - "5434:5432"
    command: >
      pg_autoctl create postgres
      --pgdata /var/lib/postgresql/node3
      --pgport 5432
      --nodename pgauto-node3
      --hostname pgauto-node3
      --name node3
    depends_on:
      - pgauto-monitor
    networks:
      - pgauto-network
    volumes:
      - pgauto-node3-data:/var/lib/postgresql/node3

volumes:
  pgauto-monitor-data:
  pgauto-node1-data:
  pgauto-node2-data:
  pgauto-node3-data:

networks:
  pgauto-network:
    driver: bridge