logger:
  level: "trace"

app:
  service:
    sendnoticeservice:
      retry-strategy:
        attempts: 10
        delay: 5s
        backoff: 1.1
  transport:
    http:
      public_host: ""
      handler:
        gin_mode: "release"