logger:
  level: "trace"

app:
  service:
    sendnoticeservice:
      retry-strategy:
        attempts: 10
        delay: 500ms
        backoff: 2.0
  transport:
    http:
      public_host: ""
      retry-strategy:
        attempts: 10
        delay: 500ms
        backoff: 2.0
      handler:
        gin_mode: "release"