logger:
  level: "trace"

app:
  service:
    sendnoticeservice:
      retry-strategy:
        attempts: 10
        delay: 5s
        backoff: 1.1
  transport:
    http:
      public_host: "https://insecurely-fond-shiner.cloudpub.ru"
      handler:
        gin_mode: "release"