app:
  service:
    sendnoticeservice:
      retry:
        attempts: 10
        delay: 5s
        backoff: 1.1
  transport:
    http:
      public_host: https://insecurely-fond-shiner.cloudpub.ru
      retry:
        attempts: 10
        delay: 5s
        backoff: 1.1
      handler:
        gin_mode: release