services:
  app:
    build:
      context: ../..
      dockerfile: providers/app/Dockerfile
      args:
        APP_NAME: ${APP_NAME}
        APP_TRANSPORT_HTTP_PORT: ${APP_TRANSPORT_HTTP_PORT}
    container_name: ${APP_CONTAINER}
    environment:
      - ENV=prod
      - APP_TRANSPORT_HTTP_PUBLIC_HOST=${APP_TRANSPORT_HTTP_PUBLIC_HOST}
      - APP_TRANSPORT_HTTP_PORT=${APP_TRANSPORT_HTTP_PORT}
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    ports:
      - "${APP_TRANSPORT_HTTP_PORT}:${APP_TRANSPORT_HTTP_PORT}"