services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: ${APP_NAME}
        APP_TRANSPORT_HTTP_PORT: ${APP_TRANSPORT_HTTP_PORT}
    container_name: ${APP_CONTAINER}
    env_file:
      - ../../.env
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "${APP_TRANSPORT_HTTP_PORT}:${APP_TRANSPORT_HTTP_PORT}"
    restart: unless-stopped
