services:
  app:
    build:
      context: ../..
      dockerfile: providers/app/Dockerfile
      args:
        APP_NAME: ${APP_NAME}
        APP_TRANSPORT_HTTP_PORT: ${APP_TRANSPORT_HTTP_PORT_EXT}
    container_name: ${APP_CONTAINER}
    environment:
      - ENV=prod
      - APP_TRANSPORT_HTTP_PUBLIC_HOST=${APP_TRANSPORT_HTTP_PUBLIC_HOST_DOCKER}
      - APP_TRANSPORT_HTTP_WEB_PUBLIC_HOST=${APP_TRANSPORT_HTTP_WEB_PUBLIC_HOST_DOCKER}
      - APP_TRANSPORT_HTTP_PORT=${APP_TRANSPORT_HTTP_PORT}
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - RABBITMQ_HOST=host.docker.internal
      - RABBITMQ_PORT=5672
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_CONTAINER}.rule=Host(`${APP_TRANSPORT_HTTP_PUBLIC_HOSTD}`) && PathPrefix(`/${APP_CONTAINER}`)"
      - "traefik.http.routers.${APP_CONTAINER}.entrypoints=web"
      - "traefik.http.services.${APP_CONTAINER}.loadbalancer.server.port=7777"
      - "traefik.http.middlewares.${APP_CONTAINER}-strip.stripprefix.prefixes=/${APP_CONTAINER}"
      - "traefik.http.routers.${APP_CONTAINER}.middlewares=${APP_CONTAINER}-strip"

networks:
  proxy:
    external: true