services:
  redis:
    image: redis:latest
    container_name: ${REDIS_CONTAINER}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --dir /data
      --appendonly yes
      --appendfilename "appendonly.aof"
      --appendfsync always
      --aof-use-rdb-preamble yes
      --save 900 1
      --save 300 10
      --save 60 10000
      --dbfilename dump.rdb
      --maxmemory 0
      --maxmemory-policy noeviction
      --stop-writes-on-bgsave-error yes

volumes:
  redis_data: